
name: "CI/CD frontend+ios"
on:
  push:
    branches:
      - main

jobs:
  code-build:
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Homebrew (if not installed)
      run: |
        if ! command -v brew &> /dev/null; then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
        
    - name: Install Docker
      run: |
        brew install --cask docker
        open /Applications/Docker.app
        brew install docker-credential-helper
        brew install awscli
        
    - name: Start Docker
      run: |
        open /Applications/Docker.app
        # Wait for Docker to start
        sleep 30

    - name: Verify Docker installation
      run: docker --version
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: arn:aws:iam::673004107015:role/ECR_ROLE_Reely-ios
        aws-region: ap-northeast-2
    - name: Login to Amazon ECR
      run: |
        echo '{"credHelpers":{"673004107015.dkr.ecr.ap-northeast-2.amazonaws.com":"ecr-login"}}' > ~/.docker/config.json
        echo '{"credsStore": ""}' > ~/.docker/config.json
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 673004107015.dkr.ecr.ap-northeast-2.amazonaws.com

      
    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ns-reely-ecr/reely-ios
        IMAGE_TAG: ${{ github.sha }}
      run: |
          export DOCKER_BUILDKIT=1
          docker buildx build -f Reely/.dockerfile --platform arm64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG Reely/.
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
    
    - name: Build iOS App
      run: |
        cd Reely/ios
        xcodebuild -scheme Reely -sdk iphonesimulator -configuration Debug
